# Generated by Django 6.0.5 on 2026-05-22 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice/inputs/')),
                ('transcription', models.TextField(blank=True)),
                ('ai_response', models.TextField(blank=True)),
                ('audio_response', models.FileField(blank=True, null=True, upload_to='voice/outputs/')),
                ('language', models.CharField(choices=[('en', 'English'), ('yo', 'Yoruba'), ('ha', 'Hausa')], default='en', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('duration_secs', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Query',
                'ordering': ['-created_at'],
            },
        ),
    ]
